### ISSUE TITLE
form组件中button绑定formtype，点击报错

### ISSUE THREAD

**Issue by xuexiangzhe** [psaren/taro-ui-vue#111] opened 2021-03-28 16:23 UTC
TypeError: Cannot read property 'triggerEvent' of undefined
![image](https://user-images.githubusercontent.com/16160367/112759307-f646f580-9024-11eb-9994-29bb8d856ebb.png)

**Comment by psaren** [comment] 2021-03-30 16:29
Duplicate of #80

**Closed by psaren** 2021-03-30 16:29 UTC

**Comment by he1237596** [comment] 2021-08-26 03:39
> TypeError: Cannot read property 'triggerEvent' of undefined
> ![image](https://user-images.githubusercontent.com/16160367/112759307-f646f580-9024-11eb-9994-29bb8d856ebb.png)

我用小程序也是
![image](https://user-images.githubusercontent.com/28428495/130896714-84a5f5a1-7524-456c-baf4-a0f65ad59c87.png)
